
<!DOCTYPE html>

<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

    <title>Excepciones incorporadas &#8212; documentación de Python - 3.10.10</title><meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pydoctheme.css?2022.1" type="text/css" />
    
    <script id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/translations.js"></script>
    
    <script src="../_static/sidebar.js"></script>
    
    <link rel="search" type="application/opensearchdescription+xml"
          title="Buscar en documentación de Python - 3.10.10"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="Sobre este documento" href="../about.html" />
    <link rel="index" title="Índice" href="../genindex.html" />
    <link rel="search" title="Búsqueda" href="../search.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="next" title="Servicios de procesamiento de texto" href="text.html" />
    <link rel="prev" title="Tipos Integrados" href="stdtypes.html" />
    <link rel="canonical" href="https://docs.python.org/3/library/exceptions.html" />
    
      
    

    
    <style>
      @media only screen {
        table.full-width-table {
            width: 100%;
        }
      }
    </style>
<link rel="shortcut icon" type="image/png" href="../_static/py.svg" />
            <script type="text/javascript" src="../_static/copybutton.js"></script>
            <script type="text/javascript" src="../_static/menu.js"></script> 

  </head>
<body>
<div class="mobile-nav">
    <input type="checkbox" id="menuToggler" class="toggler__input" aria-controls="navigation"
           aria-pressed="false" aria-expanded="false" role="button" aria-label="Menu" />
    <label for="menuToggler" class="toggler__label">
        <span></span>
    </label>
    <nav class="nav-content" role="navigation">
         <a href="https://www.python.org/" class="nav-logo">
             <img src="../_static/py.svg" alt="Logo"/>
         </a>
        <div class="version_switcher_placeholder"></div>
        <form role="search" class="search" action="../search.html" method="get">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" class="search-icon">
                <path fill-rule="nonzero"
                        d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 001.48-5.34c-.47-2.78-2.79-5-5.59-5.34a6.505 6.505 0 00-7.27 7.27c.34 2.8 2.56 5.12 5.34 5.59a6.5 6.5 0 005.34-1.48l.27.28v.79l4.25 4.25c.41.41 1.08.41 1.49 0 .41-.41.41-1.08 0-1.49L15.5 14zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z" fill="#444"></path>
            </svg>
            <input type="text" name="q" aria-label="Búsqueda rápida"/>
            <input type="submit" value="Ir"/>
        </form>
    </nav>
    <div class="menu-wrapper">
        <nav class="menu" role="navigation" aria-label="main navigation">
            <div class="language_switcher_placeholder"></div>
  <h3><a href="../contents.html">Tabla de contenido</a></h3>
  <ul>
<li><a class="reference internal" href="#">Excepciones incorporadas</a><ul>
<li><a class="reference internal" href="#exception-context">Exception context</a></li>
<li><a class="reference internal" href="#inheriting-from-built-in-exceptions">Inheriting from built-in exceptions</a></li>
<li><a class="reference internal" href="#base-classes">Clases base</a></li>
<li><a class="reference internal" href="#concrete-exceptions">Excepciones específicas</a><ul>
<li><a class="reference internal" href="#os-exceptions">Excepciones del sistema operativo</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">Advertencias</a></li>
<li><a class="reference internal" href="#exception-hierarchy">Jerarquía de excepción</a></li>
</ul>
</li>
</ul>

  <h4>Tema anterior</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="capítulo anterior">Tipos Integrados</a></p>
  <h4>Próximo tema</h4>
  <p class="topless"><a href="text.html"
                        title="próximo capítulo">Servicios de procesamiento de texto</a></p>
  <div role="note" aria-label="source link">
    <h3>Esta página</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">Reporta un Bug</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.10/Doc/library/exceptions.rst"
            rel="nofollow">Ver Fuente
        </a>
      </li>
    </ul>
  </div>
        </nav>
    </div>
</div>

  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navegación</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="Índice general"
             accesskey="I">índice</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Índice de Módulos Python"
             >módulos</a> |</li>
        <li class="right" >
          <a href="text.html" title="Servicios de procesamiento de texto"
             accesskey="N">siguiente</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="Tipos Integrados"
             accesskey="P">anterior</a> |</li>

          <li><img src="../_static/py.svg" alt="python logo" style="vertical-align: middle; margin-top: -1px"/></li>
          <li><a href="https://www.python.org/">Python</a> &#187;</li>
          <li class="switchers">
            <div class="language_switcher_placeholder"></div>
            <div class="version_switcher_placeholder"></div>
          </li>
          <li>
              
          </li>
    <li id="cpython-language-and-version">
      <a href="../index.html">3.10.10 Documentation</a> &#187;
    </li>

          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">La Biblioteca Estándar de Python</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">Excepciones incorporadas</a></li>
                <li class="right">
                    

    <div class="inline-search" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Búsqueda rápida" aria-label="Búsqueda rápida" type="text" name="q" />
          <input type="submit" value="Ir" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
                     |
                </li>
            
      </ul>
    </div>    

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <section id="built-in-exceptions">
<span id="bltin-exceptions"></span><h1>Excepciones incorporadas<a class="headerlink" href="#built-in-exceptions" title="Enlazar permanentemente con este título">¶</a></h1>
<p id="index-0">En Python, todas las excepciones deben ser instancias de una clase que se derive de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-class docutils literal notranslate"><span class="pre">BaseException</span></code></a>. En una instrucción <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> con una cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> que menciona una clase determinada, esa cláusula también controla las clases de excepción derivadas de esa clase (excepto las clases de excepción de las que se deriva <em>it</em>). Dos clases de excepción que no están relacionadas mediante subclases nunca son equivalentes, incluso si tienen el mismo nombre.</p>
<p id="index-1">Las excepciones predefinidas enumeradas a continuación pueden ser generadas por el intérprete o funciones predefinidas. Excepto donde se mencione lo contrario, tienen un <em>associated value</em> que indica la causa detallada del error. Esto podría una cadena de caracteres o una tupla elementos con grandes elementos de información (por ejemplo, un código de error y una cadena que explica el código). El valor asociado generalmente se pasa como argumentos al constructor de la clase de excepción.</p>
<p>El código de usuario puede lanzar excepciones predefinidas. Esto puede ser usado para probar un gestor de excepciones o para notificar una condición de error «igual» a la situación en la cual el intérprete lance la misma excepción; pero tenga en cuenta que no hay nada que impida que el código del usuario produzca un error inapropiado.</p>
<p>Las clases de excepción predefinidas pueden ser usadas como subclases para definir otras nuevas; se recomienda a los programadores que deriven nuevas excepciones a partir de la clase <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> o de una de sus subclases, y no de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a>. Hay disponible más información sobre la definición de excepciones en el Tutorial de Python en <a class="reference internal" href="../tutorial/errors.html#tut-userexceptions"><span class="std std-ref">Excepciones definidas por el usuario</span></a>.</p>
<section id="exception-context">
<h2>Exception context<a class="headerlink" href="#exception-context" title="Enlazar permanentemente con este título">¶</a></h2>
<p>When raising a new exception while another exception
is already being handled, the new exception’s
<code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> attribute is automatically set to the handled
exception.  An exception may be handled when an <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> or
<a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> clause, or a <a class="reference internal" href="../reference/compound_stmts.html#with"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">with</span></code></a> statement, is used.</p>
<p>This implicit exception context can be
supplemented with an explicit cause by using <code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code> with
<a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a>:</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="n">new_exc</span> <span class="kn">from</span> <span class="nn">original_exc</span>
</pre></div>
</div>
<p>La expresión que sigue a <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code></a> debe ser una excepción o <code class="docutils literal notranslate"><span class="pre">None</span></code>. Se establecerá como <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> en la excepción generada. La configuración de <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> también establece implícitamente el atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">__suppress_context__</span></code> en <code class="docutils literal notranslate"><span class="pre">True</span></code>, de modo que el uso de <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">new_exc</span> <span class="pre">from</span> <span class="pre">None</span></code> reemplaza efectivamente la excepción anterior con la nueva para fines de visualización (por ejemplo, conversión de <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyError</span></code></a> a <a class="reference internal" href="#AttributeError" title="AttributeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">AttributeError</span></code></a>), dejando la excepción anterior disponible en <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> para introspección durante la depuración.</p>
<p>La visualización por defecto de la traza de error muestra estas excepciones encadenadas además de la traza de la propia excepción. Siempre se muestra una excepción encadenada explícitamente en <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> cuando está presente. Una excepción implícitamente encadenada en <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> solo se muestra si <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> es <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">__suppress_context__</span></code> es falso.</p>
<p>En cualquier caso, la excepción en sí siempre se muestra después de cualquier excepción encadenada para que la línea final del seguimiento siempre muestre la última excepción que se generó.</p>
</section>
<section id="inheriting-from-built-in-exceptions">
<h2>Inheriting from built-in exceptions<a class="headerlink" href="#inheriting-from-built-in-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
<p>User code can create subclasses that inherit from an exception type.
It’s recommended to only subclass one exception type at a time to avoid
any possible conflicts between how the bases handle the <code class="docutils literal notranslate"><span class="pre">args</span></code>
attribute, as well as due to possible memory layout incompatibilities.</p>
<div class="impl-detail compound">
<p><strong>Detalles de implementación de CPython:</strong> Most built-in exceptions are implemented in C for efficiency, see:
<a class="reference external" href="https://github.com/python/cpython/tree/3.10/Objects/exceptions.c">Objects/exceptions.c</a>.  Some have custom memory layouts
which makes it impossible to create a subclass that inherits from
multiple exception types. The memory layout of a type is an implementation
detail and might change between Python versions, leading to new
conflicts in the future.  Therefore, it’s recommended to avoid
subclassing multiple exception types altogether.</p>
</div>
</section>
<section id="base-classes">
<h2>Clases base<a class="headerlink" href="#base-classes" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes excepciones se utilizan principalmente como clases base para otras excepciones.</p>
<dl class="py exception">
<dt id="BaseException">
<em class="property">exception </em><code class="sig-name descname">BaseException</code><a class="headerlink" href="#BaseException" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La clase base para todas las excepciones predefinidas. No está pensada para ser heredada directamente por las clases definidas por el usuario (para eso, use <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>). Si se llama a <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal notranslate"><span class="pre">str()</span></code></a> en una instancia de esta clase, se retorna la representación de los argumentos de la instancia o la cadena vacía cuando no había argumentos.</p>
<dl class="py attribute">
<dt id="BaseException.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#BaseException.args" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La tupla de argumentos dada al constructor de excepción. Algunas excepciones predefinidas (como <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>) esperan un cierto número de argumentos y asignan un significado especial a los elementos de esta tupla, mientras que otras normalmente se llaman solo con una sola cadena que da un mensaje de error.</p>
</dd></dl>

<dl class="py method">
<dt id="BaseException.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><em class="sig-param"><span class="n">tb</span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseException.with_traceback" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Este método establece <em>tb</em> como el nuevo rastreo para la excepción y retorna el objeto de excepción. Se usaba con más frecuencia antes de que las características de encadenamiento de excepciones de <span class="target" id="index-20"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a> estuvieran disponibles. El siguiente ejemplo muestra cómo podemos convertir una instancia de <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> en una instancia de <code class="docutils literal notranslate"><span class="pre">OtherException</span></code> mientras se conserva el rastreo. Una vez generado, el marco actual se inserta en el rastreo del <code class="docutils literal notranslate"><span class="pre">OtherException</span></code>, como habría sucedido con el rastreo del <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> original si hubiéramos permitido que se propagara al llamador.</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
    <span class="n">tb</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">2</span><span class="p">]</span>
    <span class="k">raise</span> <span class="n">OtherException</span><span class="p">(</span><span class="o">...</span><span class="p">)</span><span class="o">.</span><span class="n">with_traceback</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
</pre></div>
</div>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="Exception">
<em class="property">exception </em><code class="sig-name descname">Exception</code><a class="headerlink" href="#Exception" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Todas las excepciones predefinidas <em>non-system-exiting</em>, que no salen del sistema se derivan de esta clase. Todas las excepciones definidas por el usuario también deben derivarse de esta clase.</p>
</dd></dl>

<dl class="py exception">
<dt id="ArithmeticError">
<em class="property">exception </em><code class="sig-name descname">ArithmeticError</code><a class="headerlink" href="#ArithmeticError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La clase base para las excepciones predefinidas que se generan para varios errores aritméticos: <a class="reference internal" href="#OverflowError" title="OverflowError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OverflowError</span></code></a>, <a class="reference internal" href="#ZeroDivisionError" title="ZeroDivisionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code></a>, <a class="reference internal" href="#FloatingPointError" title="FloatingPointError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">FloatingPointError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="BufferError">
<em class="property">exception </em><code class="sig-name descname">BufferError</code><a class="headerlink" href="#BufferError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando <a class="reference internal" href="../c-api/buffer.html#bufferobjects"><span class="std std-ref">buffer</span></a> no se puede realizar una operación relacionada.</p>
</dd></dl>

<dl class="py exception">
<dt id="LookupError">
<em class="property">exception </em><code class="sig-name descname">LookupError</code><a class="headerlink" href="#LookupError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La clase base para las excepciones que se generan cuando una clave o índice utilizado en un mapa o secuencia que no es válido: <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndexError</span></code></a>, <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyError</span></code></a>. Esto se puede lanzar directamente por <a class="reference internal" href="codecs.html#codecs.lookup" title="codecs.lookup"><code class="xref py py-func docutils literal notranslate"><span class="pre">codecs.lookup()</span></code></a>.</p>
</dd></dl>

</section>
<section id="concrete-exceptions">
<h2>Excepciones específicas<a class="headerlink" href="#concrete-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes excepciones son las excepciones que normalmente se generan.</p>
<dl class="py exception">
<dt id="AssertionError">
<em class="property">exception </em><code class="sig-name descname">AssertionError</code><a class="headerlink" href="#AssertionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p id="index-3">Se genera cuando se produce un error en una instrucción <a class="reference internal" href="../reference/simple_stmts.html#assert"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">assert</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="AttributeError">
<em class="property">exception </em><code class="sig-name descname">AttributeError</code><a class="headerlink" href="#AttributeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error en una referencia de atributo (ver <a class="reference internal" href="../reference/expressions.html#attribute-references"><span class="std std-ref">Referencias de atributos</span></a>) o la asignación falla. (Cuando un objeto no admite referencias de atributos o asignaciones de atributos en absoluto, se genera <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>.)</p>
<p>Los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">obj</span></code> se pueden configurar utilizando argumentos de solo palabras clave para el constructor. Cuando se establecen, representan el nombre del atributo al que se intentó acceder y el objeto al que se accedió para dicho atributo, respectivamente.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.10: </span>Se agregaron los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">obj</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="EOFError">
<em class="property">exception </em><code class="sig-name descname">EOFError</code><a class="headerlink" href="#EOFError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando la función <a class="reference internal" href="functions.html#input" title="input"><code class="xref py py-func docutils literal notranslate"><span class="pre">input()</span></code></a> alcanza una condición de fin de archivo (EOF) sin leer ningún dato. (Note que el <code class="xref py py-meth docutils literal notranslate"><span class="pre">io.</span> <span class="pre">IOBase.read()</span></code> y <a class="reference internal" href="io.html#io.IOBase.readline" title="io.IOBase.readline"><code class="xref py py-meth docutils literal notranslate"><span class="pre">io.IOBase.readline()</span></code></a> retornan una cadena vacía cuando llegan a EOF.)</p>
</dd></dl>

<dl class="py exception">
<dt id="FloatingPointError">
<em class="property">exception </em><code class="sig-name descname">FloatingPointError</code><a class="headerlink" href="#FloatingPointError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>No se usa actualmente.</p>
</dd></dl>

<dl class="py exception">
<dt id="GeneratorExit">
<em class="property">exception </em><code class="sig-name descname">GeneratorExit</code><a class="headerlink" href="#GeneratorExit" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando un <a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">generator</span></a> o <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">coroutine</span></a> está cerrado; ver <a class="reference internal" href="../reference/expressions.html#generator.close" title="generator.close"><code class="xref py py-meth docutils literal notranslate"><span class="pre">generator.close()</span></code></a> y <a class="reference internal" href="../reference/datamodel.html#coroutine.close" title="coroutine.close"><code class="xref py py-meth docutils literal notranslate"><span class="pre">coroutine.close()</span></code></a>. Hereda directamente de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> en lugar de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> ya que técnicamente no es un error.</p>
</dd></dl>

<dl class="py exception">
<dt id="ImportError">
<em class="property">exception </em><code class="sig-name descname">ImportError</code><a class="headerlink" href="#ImportError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando la instrucción <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a> tiene problemas al intentar cargar un módulo. También se produce cuando la <em>from list</em> en <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></code> tiene un nombre que no se puede encontrar.</p>
<p>Los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">path</span></code> solo se pueden establecer utilizando argumentos de palabra clave en el constructor. Cuando se establece, representan el nombre del módulo que se intentó importar y la ruta de acceso a cualquier archivo que desencadenó la excepción, respectivamente.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.3: </span>Se han añadido los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">path</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="ModuleNotFoundError">
<em class="property">exception </em><code class="sig-name descname">ModuleNotFoundError</code><a class="headerlink" href="#ModuleNotFoundError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una subclase de <a class="reference internal" href="#ImportError" title="ImportError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ImportError</span></code></a> que se genera mediante <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a> cuando no se pudo encontrar un módulo. También se genera cuando <code class="docutils literal notranslate"><span class="pre">None</span></code> se encuentra en <a class="reference internal" href="sys.html#sys.modules" title="sys.modules"><code class="xref py py-data docutils literal notranslate"><span class="pre">sys.modules</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.6.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="IndexError">
<em class="property">exception </em><code class="sig-name descname">IndexError</code><a class="headerlink" href="#IndexError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando un subíndice de secuencia está fuera del rango. (Los índices de la rebanada son truncados silenciosamente para caer en el intervalo permitido; si un índice no es un entero, se genera <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>.)</p>
</dd></dl>

<dl class="py exception">
<dt id="KeyError">
<em class="property">exception </em><code class="sig-name descname">KeyError</code><a class="headerlink" href="#KeyError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando no se encuentra una clave de asignación (diccionario) en el conjunto de claves existentes (mapa).</p>
</dd></dl>

<dl class="py exception">
<dt id="KeyboardInterrupt">
<em class="property">exception </em><code class="sig-name descname">KeyboardInterrupt</code><a class="headerlink" href="#KeyboardInterrupt" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el usuario pulsa la tecla de interrupción (normalmente <kbd class="kbd docutils literal notranslate"><kbd class="kbd docutils literal notranslate">Control</kbd>-<kbd class="kbd docutils literal notranslate">C</kbd></kbd> o <kbd class="kbd docutils literal notranslate">Delete</kbd>). Durante la ejecución, se realiza una comprobación de interrupciones con regularidad. La excepción hereda de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> para no ser detectada de forma accidental por <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> y, por lo tanto, prevenir que el intérprete salga.</p>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p>Catching a <a class="reference internal" href="#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a> requires special consideration.
Because it can be raised at unpredictable points, it may, in some
circumstances, leave the running program in an inconsistent state. It is
generally best to allow <a class="reference internal" href="#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a> to end the program as
quickly as possible or avoid raising it entirely. (See
<a class="reference internal" href="signal.html#handlers-and-exceptions"><span class="std std-ref">Note on Signal Handlers and Exceptions</span></a>.)</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="MemoryError">
<em class="property">exception </em><code class="sig-name descname">MemoryError</code><a class="headerlink" href="#MemoryError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una operación se queda sin memoria pero la situación aún puede ser recuperada (eliminando algunos objetos). El valor asociado es una cadena que indica que tipo de operación (interna) se quedó sin memoria. Tenga en cuenta que debido a la arquitectura de administración de memoria (función <code class="xref c c-func docutils literal notranslate"><span class="pre">malloc()</span></code> de C), el intérprete no siempre puede recuperarse completamente de esta situación; sin embargo, plantea una excepción para que se pueda imprimir un seguimiento de la pila, en caso de que un programa fuera de servicio fuera lo causa.</p>
</dd></dl>

<dl class="py exception">
<dt id="NameError">
<em class="property">exception </em><code class="sig-name descname">NameError</code><a class="headerlink" href="#NameError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando no se encuentra un nombre local o global. Esto se aplica solo a nombres no calificados. El valor asociado es un mensaje de error que incluye el nombre que no se pudo encontrar.</p>
<p>El atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> se puede establecer utilizando un argumento de solo palabra clave para el constructor. Cuando se establece, representa el nombre de la variable a la que se intentó acceder.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.10: </span>Se agregó el atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="NotImplementedError">
<em class="property">exception </em><code class="sig-name descname">NotImplementedError</code><a class="headerlink" href="#NotImplementedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción se deriva de <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>. En las clases base definidas por el usuario, los métodos abstractos deberían lanzar esta excepción cuando requieren clases derivadas para anular el método, o mientras se desarrolla la clase para indicar que la implementación real aún necesita ser agregada.</p>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p>No debe usarse para indicar que un operador o método no debe ser admitido en absoluto – en ese caso, deje el operador / método sin definir o, si es una subclase, se establece en <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-data docutils literal notranslate"><span class="pre">None</span></code></a>.</p>
</div>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p><code class="docutils literal notranslate"><span class="pre">NotImplementedError</span></code> y <code class="docutils literal notranslate"><span class="pre">NotImplemented</span></code> no son intercambiables, a pesar de que tienen nombres y propósitos similares. Consulte <a class="reference internal" href="constants.html#NotImplemented" title="NotImplemented"><code class="xref py py-data docutils literal notranslate"><span class="pre">NotImplemented</span></code></a> para obtener detalles sobre cuándo usarlo.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="OSError">
<em class="property">exception </em><code class="sig-name descname">OSError</code><span class="sig-paren">(</span><span class="optional">[</span><em class="sig-param">arg</em><span class="optional">]</span><span class="sig-paren">)</span><a class="headerlink" href="#OSError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dt>
<em class="property">exception </em><code class="sig-name descname">OSError</code><span class="sig-paren">(</span><em class="sig-param">errno</em>, <em class="sig-param">strerror</em><span class="optional">[</span>, <em class="sig-param">filename</em><span class="optional">[</span>, <em class="sig-param">winerror</em><span class="optional">[</span>, <em class="sig-param">filename2</em><span class="optional">]</span><span class="optional">]</span><span class="optional">]</span><span class="sig-paren">)</span></dt>
<dd><p id="index-4">Esta excepción se produce cuando una función del sistema retorna un error relacionado con el sistema, que incluye fallas de E/S como <code class="docutils literal notranslate"><span class="pre">file</span> <span class="pre">not</span> <span class="pre">found</span></code> o <code class="docutils literal notranslate"><span class="pre">disk</span> <span class="pre">full</span></code> (no para tipos de argumentos ilegales u otros errores incidentales).</p>
<p>La segunda forma del constructor establece los atributos correspondientes, que se describen a continuación. Los atributos predeterminados son <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a> si no se especifican. Para compatibilidad con versiones anteriores, si se pasan tres argumentos, el atributo <a class="reference internal" href="#BaseException.args" title="BaseException.args"><code class="xref py py-attr docutils literal notranslate"><span class="pre">args</span></code></a> contiene solo una tupla de 2 de los dos primeros argumentos del constructor.</p>
<p>El constructor a menudo retorna una subclase de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, como se describe en <a class="reference internal" href="#os-exceptions">OS exceptions</a> a continuación. La subclase particular depende del valor final <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a>. Este comportamiento solo ocurre cuando se construye <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a> directamente o mediante un alias, y no se hereda al derivar.</p>
<dl class="py attribute">
<dt id="OSError.errno">
<code class="sig-name descname">errno</code><a class="headerlink" href="#OSError.errno" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Un código de error numérico de la variable C, <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code>.</p>
</dd></dl>

<dl class="py attribute">
<dt id="OSError.winerror">
<code class="sig-name descname">winerror</code><a class="headerlink" href="#OSError.winerror" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>En Windows, esto le proporciona el código de error nativo de Windows. El atributo <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a> es entonces una traducción aproximada, en términos POSIX, de ese código de error nativo.</p>
<p>En Windows, si el argumento del constructor <code class="docutils literal notranslate"><span class="pre">winerror</span></code> es un entero, el atributo <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a> se determina a partir del código de error de Windows y el argumento <code class="docutils literal notranslate"><span class="pre">errno</span></code> se ignora. En otras plataformas, el argumento <code class="docutils literal notranslate"><span class="pre">winerror</span></code> se ignora y el atributo <a class="reference internal" href="#OSError.winerror" title="OSError.winerror"><code class="xref py py-attr docutils literal notranslate"><span class="pre">winerror</span></code></a> no existe.</p>
</dd></dl>

<dl class="py attribute">
<dt id="OSError.strerror">
<code class="sig-name descname">strerror</code><a class="headerlink" href="#OSError.strerror" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El mensaje de error correspondiente, tal como lo proporciona el sistema operativo. Está formateado por las funciones de C, <code class="xref c c-func docutils literal notranslate"><span class="pre">perror()</span></code> en POSIX, y <code class="xref c c-func docutils literal notranslate"><span class="pre">FormatMessage()</span></code> en Windows.</p>
</dd></dl>

<dl class="py attribute">
<dt id="OSError.filename">
<code class="sig-name descname">filename</code><a class="headerlink" href="#OSError.filename" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dt id="OSError.filename2">
<code class="sig-name descname">filename2</code><a class="headerlink" href="#OSError.filename2" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Para las excepciones que involucran una ruta del sistema de archivos (como <a class="reference internal" href="functions.html#open" title="open"><code class="xref py py-func docutils literal notranslate"><span class="pre">open()</span></code></a> o <a class="reference internal" href="os.html#os.unlink" title="os.unlink"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.unlink()</span></code></a>), <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename</span></code></a> es el nombre del archivo pasado a la función. Para las funciones que involucran dos rutas del sistema de archivos (como <a class="reference internal" href="os.html#os.rename" title="os.rename"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.rename()</span></code></a>), <a class="reference internal" href="#OSError.filename2" title="OSError.filename2"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename2</span></code></a> corresponde al segundo nombre de archivo pasado a la función.</p>
</dd></dl>

<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.3: </span><a class="reference internal" href="#EnvironmentError" title="EnvironmentError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">EnvironmentError</span></code></a>, <a class="reference internal" href="#IOError" title="IOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IOError</span></code></a>, <a class="reference internal" href="#WindowsError" title="WindowsError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">WindowsError</span></code></a>, <a class="reference internal" href="socket.html#socket.error" title="socket.error"><code class="xref py py-exc docutils literal notranslate"><span class="pre">socket.error</span></code></a>, <a class="reference internal" href="select.html#select.error" title="select.error"><code class="xref py py-exc docutils literal notranslate"><span class="pre">select.error</span></code></a> y <code class="xref py py-exc docutils literal notranslate"><span class="pre">mmap.error</span></code> se han fusionado en <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, y el constructor puede retornar una subclase.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.4: </span>El atributo <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename</span></code></a> es ahora el nombre de archivo original pasado a la función, en lugar del nombre codificado o decodificado desde <a class="reference internal" href="../glossary.html#term-filesystem-encoding-and-error-handler"><span class="xref std std-term">filesystem encoding and error handler</span></a>. Además, se agregaron el argumento y atributo del constructor <em>filename2</em>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="OverflowError">
<em class="property">exception </em><code class="sig-name descname">OverflowError</code><a class="headerlink" href="#OverflowError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el resultado de una operación aritmética es demasiado grande para ser representado. Esto no puede ocurrir para los enteros (para lo cual es mejor lanzar <a class="reference internal" href="#MemoryError" title="MemoryError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MemoryError</span></code></a> que darse por vencido). Sin embargo, por razones históricas, <code class="docutils literal notranslate"><span class="pre">OverflowError</span></code> a veces se genera para enteros que están fuera del rango requerido. Debido a la falta de estandarización del manejo de excepciones de coma flotante en C, la mayoría de las operaciones de coma flotante no se verifican.</p>
</dd></dl>

<dl class="py exception">
<dt id="RecursionError">
<em class="property">exception </em><code class="sig-name descname">RecursionError</code><a class="headerlink" href="#RecursionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción se deriva de <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>. Se lanza cuando el intérprete detecta que se excede la profundidad máxima de recursión (ver <a class="reference internal" href="sys.html#sys.getrecursionlimit" title="sys.getrecursionlimit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.getrecursionlimit()</span></code></a>).</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.5: </span>Anteriormente, se planteó un simple <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="ReferenceError">
<em class="property">exception </em><code class="sig-name descname">ReferenceError</code><a class="headerlink" href="#ReferenceError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción se produce cuando un proxy de referencia débil, creado por la función <a class="reference internal" href="weakref.html#weakref.proxy" title="weakref.proxy"><code class="xref py py-func docutils literal notranslate"><span class="pre">weakref.proxy()</span></code></a>, se utiliza para acceder a un atributo del referente después de que se ha recolectado basura. Para obtener más información sobre referencias débiles, consulte el módulo <a class="reference internal" href="weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code class="xref py py-mod docutils literal notranslate"><span class="pre">weakref</span></code></a> .</p>
</dd></dl>

<dl class="py exception">
<dt id="RuntimeError">
<em class="property">exception </em><code class="sig-name descname">RuntimeError</code><a class="headerlink" href="#RuntimeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se detecta un error que no corresponde a ninguna de las otras categorías. El valor asociado es una cadena que indica exactamente qué salió mal.</p>
</dd></dl>

<dl class="py exception">
<dt id="StopIteration">
<em class="property">exception </em><code class="sig-name descname">StopIteration</code><a class="headerlink" href="#StopIteration" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Generado por la función incorporada <a class="reference internal" href="functions.html#next" title="next"><code class="xref py py-func docutils literal notranslate"><span class="pre">next()</span></code></a> y un <a class="reference internal" href="../glossary.html#term-iterator"><span class="xref std std-term">iterator</span></a>'s <a class="reference internal" href="stdtypes.html#iterator.__next__" title="iterator.__next__"><code class="xref py py-meth docutils literal notranslate"><span class="pre">__next__()</span></code></a> para indicar que no hay más elementos producidos por el iterador.</p>
<p>El objeto de excepción tiene un solo atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">value</span></code>, que se proporciona como argumento al construir la excepción, y por defecto es <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a>.</p>
<p>Cuando se retorna una función <a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">generator</span></a> o <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">coroutine</span></a>, se genera una nueva instancia <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a>, y el valor retornado por la función se utiliza como parámetro <code class="xref py py-attr docutils literal notranslate"><span class="pre">value</span></code> para constructor de la excepción.</p>
<p>Si un generador lanza directa o indirectamente <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a>, se convierte en <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a> (conservando <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> como la causa de la nueva excepción).</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.3: </span>Se agregó el atributo <cite>*value*</cite> y la capacidad de las funciones del generador de usarlo para retornar un valor.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.5: </span>Introdujo la transformación <em>RuntimeError</em> a través de <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">__future__</span> <span class="pre">import</span> <span class="pre">generator_stop</span></code>, ver <span class="target" id="index-21"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0479"><strong>PEP 479</strong></a>.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.7: </span>Habilitar <span class="target" id="index-22"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0479"><strong>PEP 479</strong></a> para todo el código por defecto: a <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> generado en un generador se transforma en <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="StopAsyncIteration">
<em class="property">exception </em><code class="sig-name descname">StopAsyncIteration</code><a class="headerlink" href="#StopAsyncIteration" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se debe lanzar mediante <code class="xref py py-meth docutils literal notranslate"><span class="pre">__anext__()</span></code> de un objeto <a class="reference internal" href="../glossary.html#term-asynchronous-iterator"><span class="xref std std-term">asynchronous iterator</span></a> para detener la iteración.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.5.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="SyntaxError">
<em class="property">exception </em><code class="sig-name descname">SyntaxError</code><span class="sig-paren">(</span><em class="sig-param"><span class="n">message</span></em>, <em class="sig-param"><span class="n">details</span></em><span class="sig-paren">)</span><a class="headerlink" href="#SyntaxError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el analizador encuentra un error de sintaxis. Esto puede ocurrir en una instrucción <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a>, en una llamada a las funciones integradas <a class="reference internal" href="functions.html#compile" title="compile"><code class="xref py py-func docutils literal notranslate"><span class="pre">compile()</span></code></a>, <a class="reference internal" href="functions.html#exec" title="exec"><code class="xref py py-func docutils literal notranslate"><span class="pre">exec()</span></code></a> o <a class="reference internal" href="functions.html#eval" title="eval"><code class="xref py py-func docutils literal notranslate"><span class="pre">eval()</span></code></a>, o al leer el script inicial o la entrada estándar (también de forma interactiva).</p>
<p>El <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal notranslate"><span class="pre">str()</span></code></a> de la instancia de excepción retorna solo el mensaje de error. Detalles es una tupla cuyos miembros también están disponibles como atributos separados.</p>
<dl class="py attribute">
<dt id="SyntaxError.filename">
<code class="sig-name descname">filename</code><a class="headerlink" href="#SyntaxError.filename" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El nombre del archivo en el que se produjo el error de sintaxis.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.lineno">
<code class="sig-name descname">lineno</code><a class="headerlink" href="#SyntaxError.lineno" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>En qué número de línea del archivo se produjo el error. Tiene un índice 1: la primera línea del archivo tiene un <code class="docutils literal notranslate"><span class="pre">lineno</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.offset">
<code class="sig-name descname">offset</code><a class="headerlink" href="#SyntaxError.offset" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La columna de la línea donde ocurrió el error. Está indexado a 1: el primer carácter de la línea tiene un <code class="docutils literal notranslate"><span class="pre">offset</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.text">
<code class="sig-name descname">text</code><a class="headerlink" href="#SyntaxError.text" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El texto del código fuente involucrado en el error.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.end_lineno">
<code class="sig-name descname">end_lineno</code><a class="headerlink" href="#SyntaxError.end_lineno" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>En qué número de línea del archivo termina el error. Está indexado a 1: la primera línea del archivo tiene un <code class="docutils literal notranslate"><span class="pre">lineno</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt id="SyntaxError.end_offset">
<code class="sig-name descname">end_offset</code><a class="headerlink" href="#SyntaxError.end_offset" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Finaliza la columna de la línea final donde ocurrió el error. Está indexado a 1: el primer carácter de la línea tiene un <code class="docutils literal notranslate"><span class="pre">offset</span></code> de 1.</p>
</dd></dl>

<p>Para errores en los campos de cadena f, el mensaje tiene el prefijo «cadena f:» y las compensaciones son compensaciones en un texto construido a partir de la expresión de reemplazo. Por ejemplo, compilar f’Bad {ab} field “da como resultado este atributo args: (” f-string: … “, (” “, 1, 2,” (ab) n “, 1, 5)) .</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.10: </span>Se agregaron los atributos <a class="reference internal" href="#SyntaxError.end_lineno" title="SyntaxError.end_lineno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">end_lineno</span></code></a> y <a class="reference internal" href="#SyntaxError.end_offset" title="SyntaxError.end_offset"><code class="xref py py-attr docutils literal notranslate"><span class="pre">end_offset</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="IndentationError">
<em class="property">exception </em><code class="sig-name descname">IndentationError</code><a class="headerlink" href="#IndentationError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para errores de sintaxis relacionados con sangría incorrecta. Esta es una subclase de <a class="reference internal" href="#SyntaxError" title="SyntaxError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">SyntaxError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="TabError">
<em class="property">exception </em><code class="sig-name descname">TabError</code><a class="headerlink" href="#TabError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando la sangría contiene un uso inconsistente de pestañas y espacios. Esta es una subclase de <a class="reference internal" href="#IndentationError" title="IndentationError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndentationError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="SystemError">
<em class="property">exception </em><code class="sig-name descname">SystemError</code><a class="headerlink" href="#SystemError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el intérprete encuentra un error interno, pero la situación no parece tan grave como para abandonar toda esperanza. El valor asociado es una cadena que indica qué salió mal (a bajo nivel).</p>
<p>Debe informar esto al autor o responsable de su intérprete de Python. Asegúrese de informar la versión del intérprete de Python (<code class="docutils literal notranslate"><span class="pre">sys.version</span></code>; también se imprime al comienzo de una sesión interactiva de Python), el mensaje de error exacto (el valor asociado de la excepción) y, si es posible, la fuente del programa que activó el error.</p>
</dd></dl>

<dl class="py exception">
<dt id="SystemExit">
<em class="property">exception </em><code class="sig-name descname">SystemExit</code><a class="headerlink" href="#SystemExit" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción es provocada por la función <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a>. Hereda de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> en lugar de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> para que no sea gestionada accidentalmente por el código que captura <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>. Esto permite que la excepción se propague correctamente y que el intérprete salga. Cuando no se maneja, el intérprete de Python sale; no se imprime el seguimiento de pila. El constructor acepta el mismo argumento opcional pasado a <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a>. Si el valor es un entero, especifica el estado de salida del sistema (se pasa a la función <code class="xref c c-func docutils literal notranslate"><span class="pre">exit()</span></code> de C); si es <code class="docutils literal notranslate"><span class="pre">None</span></code>, el estado de salida es cero; Si tiene otro tipo (como una cadena), se imprime el valor del objeto y el estado de salida es uno.</p>
<p>Una llamada <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a> se traduce en una excepción para que los gestores de limpieza (<a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> cláusulas de <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a>) puedan ejecutarse, y para que un depurador pueda ejecutar un <em>script</em> sin correr el riesgo de perder el control. La función <a class="reference internal" href="os.html#os._exit" title="os._exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">os._exit()</span></code></a> se puede usar si es absolutamente necesario salir (por ejemplo, en el proceso secundario después de una llamada a <a class="reference internal" href="os.html#os.fork" title="os.fork"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.fork()</span></code></a>).</p>
<dl class="py attribute">
<dt id="SystemExit.code">
<code class="sig-name descname">code</code><a class="headerlink" href="#SystemExit.code" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El estado de salida o mensaje de error que se pasa al constructor. (El valor predeterminado es <code class="docutils literal notranslate"><span class="pre">None</span></code>.)</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="TypeError">
<em class="property">exception </em><code class="sig-name descname">TypeError</code><a class="headerlink" href="#TypeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una operación o función se aplica a un objeto de tipo inapropiado. El valor asociado es una cadena que proporciona detalles sobre la falta de coincidencia de tipos.</p>
<p>El código de usuario puede lanzar esta excepción para indicar que un intento de operación en un objeto no es compatible y no debe serlo. Si un objeto está destinado a soportar una operación dada pero aún no ha proporcionado una implementación, <a class="reference internal" href="#NotImplementedError" title="NotImplementedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NotImplementedError</span></code></a> es la excepción adecuada para lanzar.</p>
<p>Pasar argumentos del tipo incorrecto (por ejemplo, pasar a <a class="reference internal" href="stdtypes.html#list" title="list"><code class="xref py py-class docutils literal notranslate"><span class="pre">list</span></code></a> cuando se espera un <a class="reference internal" href="functions.html#int" title="int"><code class="xref py py-class docutils literal notranslate"><span class="pre">int</span></code></a>) debería dar como resultado <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>, pero pasar argumentos con el valor incorrecto (por ejemplo, un número fuera límites esperados) debería dar como resultado <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValueError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnboundLocalError">
<em class="property">exception </em><code class="sig-name descname">UnboundLocalError</code><a class="headerlink" href="#UnboundLocalError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se hace referencia a una variable local en una función o método, pero no se ha vinculado ningún valor a esa variable. Esta es una subclase de <a class="reference internal" href="#NameError" title="NameError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NameError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeError">
<em class="property">exception </em><code class="sig-name descname">UnicodeError</code><a class="headerlink" href="#UnicodeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error de codificación o decodificación relacionado con Unicode. Es una subclase de <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValueError</span></code></a>.</p>
<p><a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a> tiene atributos que describen el error de codificación o decodificación. Por ejemplo, <code class="docutils literal notranslate"><span class="pre">err.object[err.start:err.end]</span></code> proporciona la entrada inválida particular en la que falló el códec.</p>
<dl class="py attribute">
<dt id="UnicodeError.encoding">
<code class="sig-name descname">encoding</code><a class="headerlink" href="#UnicodeError.encoding" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El nombre de la codificación que provocó el error.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.reason">
<code class="sig-name descname">reason</code><a class="headerlink" href="#UnicodeError.reason" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una cadena que describe el error de códec específico.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.object">
<code class="sig-name descname">object</code><a class="headerlink" href="#UnicodeError.object" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El objeto que el códec intentaba codificar o decodificar.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.start">
<code class="sig-name descname">start</code><a class="headerlink" href="#UnicodeError.start" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El primer índice de datos no válidos en <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal notranslate"><span class="pre">object</span></code></a>.</p>
</dd></dl>

<dl class="py attribute">
<dt id="UnicodeError.end">
<code class="sig-name descname">end</code><a class="headerlink" href="#UnicodeError.end" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El índice después de los últimos datos no válidos en <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal notranslate"><span class="pre">object</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="UnicodeEncodeError">
<em class="property">exception </em><code class="sig-name descname">UnicodeEncodeError</code><a class="headerlink" href="#UnicodeEncodeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error relacionado con Unicode durante la codificación. Es una subclase de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeDecodeError">
<em class="property">exception </em><code class="sig-name descname">UnicodeDecodeError</code><a class="headerlink" href="#UnicodeDecodeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error relacionado con Unicode durante la codificación. Es una subclase de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeTranslateError">
<em class="property">exception </em><code class="sig-name descname">UnicodeTranslateError</code><a class="headerlink" href="#UnicodeTranslateError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error relacionado con Unicode durante la codificación. Es una subclase de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ValueError">
<em class="property">exception </em><code class="sig-name descname">ValueError</code><a class="headerlink" href="#ValueError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una operación o función recibe un argumento que tiene el tipo correcto pero un valor inapropiado, y la situación no se describe con una excepción más precisa como <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndexError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ZeroDivisionError">
<em class="property">exception </em><code class="sig-name descname">ZeroDivisionError</code><a class="headerlink" href="#ZeroDivisionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el segundo argumento de una operación de división o módulo es cero. El valor asociado es una cadena que indica el tipo de operandos y la operación.</p>
</dd></dl>

<p>Las siguientes excepciones se mantienen por compatibilidad con versiones anteriores; a partir de Python 3.3, son alias de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>.</p>
<dl class="py exception">
<dt id="EnvironmentError">
<em class="property">exception </em><code class="sig-name descname">EnvironmentError</code><a class="headerlink" href="#EnvironmentError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt id="IOError">
<em class="property">exception </em><code class="sig-name descname">IOError</code><a class="headerlink" href="#IOError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt id="WindowsError">
<em class="property">exception </em><code class="sig-name descname">WindowsError</code><a class="headerlink" href="#WindowsError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Solo disponible en Windows.</p>
</dd></dl>

<section id="os-exceptions">
<h3>Excepciones del sistema operativo<a class="headerlink" href="#os-exceptions" title="Enlazar permanentemente con este título">¶</a></h3>
<p>Las siguientes excepciones son subclases de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, se generan según el código de error del sistema.</p>
<dl class="py exception">
<dt id="BlockingIOError">
<em class="property">exception </em><code class="sig-name descname">BlockingIOError</code><a class="headerlink" href="#BlockingIOError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when an operation would block on an object (e.g. socket) set
for non-blocking operation.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EAGAIN" title="errno.EAGAIN"><code class="xref py py-data docutils literal notranslate"><span class="pre">EAGAIN</span></code></a>, <a class="reference internal" href="errno.html#errno.EALREADY" title="errno.EALREADY"><code class="xref py py-data docutils literal notranslate"><span class="pre">EALREADY</span></code></a>,
<a class="reference internal" href="errno.html#errno.EWOULDBLOCK" title="errno.EWOULDBLOCK"><code class="xref py py-data docutils literal notranslate"><span class="pre">EWOULDBLOCK</span></code></a> and <a class="reference internal" href="errno.html#errno.EINPROGRESS" title="errno.EINPROGRESS"><code class="xref py py-data docutils literal notranslate"><span class="pre">EINPROGRESS</span></code></a>.</p>
<p>Además de los de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, <a class="reference internal" href="#BlockingIOError" title="BlockingIOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BlockingIOError</span></code></a> puede tener un atributo más:</p>
<dl class="py attribute">
<dt id="BlockingIOError.characters_written">
<code class="sig-name descname">characters_written</code><a class="headerlink" href="#BlockingIOError.characters_written" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Un entero que contiene el número de caracteres escritos en la secuencia antes de que se bloquee. Este atributo está disponible cuando se utilizan las clases de E/S almacenadas en el modulo <a class="reference internal" href="io.html#module-io" title="io: Core tools for working with streams."><code class="xref py py-mod docutils literal notranslate"><span class="pre">io</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="ChildProcessError">
<em class="property">exception </em><code class="sig-name descname">ChildProcessError</code><a class="headerlink" href="#ChildProcessError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when an operation on a child process failed.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECHILD" title="errno.ECHILD"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECHILD</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionError">
<em class="property">exception </em><code class="sig-name descname">ConnectionError</code><a class="headerlink" href="#ConnectionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una clase base para problemas relacionados con la conexión.</p>
<p>Las subclases son <a class="reference internal" href="#BrokenPipeError" title="BrokenPipeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BrokenPipeError</span></code></a>, <a class="reference internal" href="#ConnectionAbortedError" title="ConnectionAbortedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionAbortedError</span></code></a>, <a class="reference internal" href="#ConnectionRefusedError" title="ConnectionRefusedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionRefusedError</span></code></a> y <a class="reference internal" href="#ConnectionResetError" title="ConnectionResetError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionResetError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="BrokenPipeError">
<em class="property">exception </em><code class="sig-name descname">BrokenPipeError</code><a class="headerlink" href="#BrokenPipeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when trying to write on a
pipe while the other end has been closed, or trying to write on a socket
which has been shutdown for writing.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EPIPE" title="errno.EPIPE"><code class="xref py py-data docutils literal notranslate"><span class="pre">EPIPE</span></code></a> and <a class="reference internal" href="errno.html#errno.ESHUTDOWN" title="errno.ESHUTDOWN"><code class="xref py py-data docutils literal notranslate"><span class="pre">ESHUTDOWN</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionAbortedError">
<em class="property">exception </em><code class="sig-name descname">ConnectionAbortedError</code><a class="headerlink" href="#ConnectionAbortedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when a connection attempt
is aborted by the peer.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNABORTED" title="errno.ECONNABORTED"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNABORTED</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionRefusedError">
<em class="property">exception </em><code class="sig-name descname">ConnectionRefusedError</code><a class="headerlink" href="#ConnectionRefusedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when a connection attempt
is refused by the peer.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNREFUSED" title="errno.ECONNREFUSED"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNREFUSED</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ConnectionResetError">
<em class="property">exception </em><code class="sig-name descname">ConnectionResetError</code><a class="headerlink" href="#ConnectionResetError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, raised when a connection is
reset by the peer.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNRESET" title="errno.ECONNRESET"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNRESET</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="FileExistsError">
<em class="property">exception </em><code class="sig-name descname">FileExistsError</code><a class="headerlink" href="#FileExistsError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when trying to create a file or directory which already exists.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EEXIST" title="errno.EEXIST"><code class="xref py py-data docutils literal notranslate"><span class="pre">EEXIST</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="FileNotFoundError">
<em class="property">exception </em><code class="sig-name descname">FileNotFoundError</code><a class="headerlink" href="#FileNotFoundError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when a file or directory is requested but doesn’t exist.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ENOENT" title="errno.ENOENT"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOENT</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="InterruptedError">
<em class="property">exception </em><code class="sig-name descname">InterruptedError</code><a class="headerlink" href="#InterruptedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una llamada entrante interrumpe una llamada del sistema. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EINTR" title="errno.EINTR"><code class="xref py py-data docutils literal notranslate"><span class="pre">EINTR</span></code></a>.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.5: </span>Python ahora vuelve a intentar las llamadas del sistema cuando una señal interrumpe un <em>syscall</em>, excepto si el gestor de señales lanza una excepción (ver <span class="target" id="index-23"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0475"><strong>PEP 475</strong></a> para la justificación), en lugar de lanzar <a class="reference internal" href="#InterruptedError" title="InterruptedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">InterruptedError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="IsADirectoryError">
<em class="property">exception </em><code class="sig-name descname">IsADirectoryError</code><a class="headerlink" href="#IsADirectoryError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when a file operation (such as <a class="reference internal" href="os.html#os.remove" title="os.remove"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.remove()</span></code></a>) is requested
on a directory.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EISDIR" title="errno.EISDIR"><code class="xref py py-data docutils literal notranslate"><span class="pre">EISDIR</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="NotADirectoryError">
<em class="property">exception </em><code class="sig-name descname">NotADirectoryError</code><a class="headerlink" href="#NotADirectoryError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when a directory operation (such as <a class="reference internal" href="os.html#os.listdir" title="os.listdir"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.listdir()</span></code></a>) is requested on
something which is not a directory.  On most POSIX platforms, it may also be
raised if an operation attempts to open or traverse a non-directory file as if
it were a directory.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ENOTDIR" title="errno.ENOTDIR"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOTDIR</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="PermissionError">
<em class="property">exception </em><code class="sig-name descname">PermissionError</code><a class="headerlink" href="#PermissionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when trying to run an operation without the adequate access
rights - for example filesystem permissions.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EACCES" title="errno.EACCES"><code class="xref py py-data docutils literal notranslate"><span class="pre">EACCES</span></code></a> and <a class="reference internal" href="errno.html#errno.EPERM" title="errno.EPERM"><code class="xref py py-data docutils literal notranslate"><span class="pre">EPERM</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ProcessLookupError">
<em class="property">exception </em><code class="sig-name descname">ProcessLookupError</code><a class="headerlink" href="#ProcessLookupError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when a given process doesn’t exist.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ESRCH" title="errno.ESRCH"><code class="xref py py-data docutils literal notranslate"><span class="pre">ESRCH</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="TimeoutError">
<em class="property">exception </em><code class="sig-name descname">TimeoutError</code><a class="headerlink" href="#TimeoutError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Raised when a system function timed out at the system level.
Corresponds to <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ETIMEDOUT" title="errno.ETIMEDOUT"><code class="xref py py-data docutils literal notranslate"><span class="pre">ETIMEDOUT</span></code></a>.</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.3: </span>Por lo anterior se agregaron las subclases <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>.</p>
</div>
<div class="admonition seealso">
<p class="admonition-title">Ver también</p>
<p><span class="target" id="index-24"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3151"><strong>PEP 3151</strong></a> - Reelaborando el sistema operativo y la jerarquía de excepciones E/S</p>
</div>
</section>
</section>
<section id="warnings">
<span id="warning-categories-as-exceptions"></span><h2>Advertencias<a class="headerlink" href="#warnings" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes excepciones se utilizan como categorías de advertencia; consulte la documentación de <a class="reference internal" href="warnings.html#warning-categories"><span class="std std-ref">Categorías de advertencia</span></a> para obtener más detalles.</p>
<dl class="py exception">
<dt id="Warning">
<em class="property">exception </em><code class="sig-name descname">Warning</code><a class="headerlink" href="#Warning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para categorías de advertencia.</p>
</dd></dl>

<dl class="py exception">
<dt id="UserWarning">
<em class="property">exception </em><code class="sig-name descname">UserWarning</code><a class="headerlink" href="#UserWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias generadas por código de usuario.</p>
</dd></dl>

<dl class="py exception">
<dt id="DeprecationWarning">
<em class="property">exception </em><code class="sig-name descname">DeprecationWarning</code><a class="headerlink" href="#DeprecationWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre características obsoletas cuando esas advertencias están destinadas a otros desarrolladores de Python.</p>
<p>Ignorado por los filtros de advertencia predeterminados, excepto en el módulo <code class="docutils literal notranslate"><span class="pre">__main__</span></code> (<span class="target" id="index-25"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0565"><strong>PEP 565</strong></a>). Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
<p>La política de obsolescencia se describe en <span class="target" id="index-26"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0387"><strong>PEP 387</strong></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="PendingDeprecationWarning">
<em class="property">exception </em><code class="sig-name descname">PendingDeprecationWarning</code><a class="headerlink" href="#PendingDeprecationWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre características que están obsoletas y que se espera que sean obsoletas en el futuro, pero que no lo son en este momento.</p>
<p>Esta clase rara vez se usa para emitir una advertencia sobre una posible desaprobación próxima es inusual, y <a class="reference internal" href="#DeprecationWarning" title="DeprecationWarning"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DeprecationWarning</span></code></a> se prefiere para las desaprobaciones ya activas.</p>
<p>Ignorado por los filtros de advertencia predeterminados. Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
<p>La política de obsolescencia se describe en <span class="target" id="index-27"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0387"><strong>PEP 387</strong></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="SyntaxWarning">
<em class="property">exception </em><code class="sig-name descname">SyntaxWarning</code><a class="headerlink" href="#SyntaxWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre sintaxis dudosa.</p>
</dd></dl>

<dl class="py exception">
<dt id="RuntimeWarning">
<em class="property">exception </em><code class="sig-name descname">RuntimeWarning</code><a class="headerlink" href="#RuntimeWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre comportamiento dudoso en tiempo de ejecución.</p>
</dd></dl>

<dl class="py exception">
<dt id="FutureWarning">
<em class="property">exception </em><code class="sig-name descname">FutureWarning</code><a class="headerlink" href="#FutureWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre características en desuso cuando esas advertencias están destinadas a usuarios finales de aplicaciones escritas en Python.</p>
</dd></dl>

<dl class="py exception">
<dt id="ImportWarning">
<em class="property">exception </em><code class="sig-name descname">ImportWarning</code><a class="headerlink" href="#ImportWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre posibles errores en la importación de módulos.</p>
<p>Ignorado por los filtros de advertencia predeterminados. Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
</dd></dl>

<dl class="py exception">
<dt id="UnicodeWarning">
<em class="property">exception </em><code class="sig-name descname">UnicodeWarning</code><a class="headerlink" href="#UnicodeWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con Unicode.</p>
</dd></dl>

<dl class="py exception">
<dt id="EncodingWarning">
<em class="property">exception </em><code class="sig-name descname">EncodingWarning</code><a class="headerlink" href="#EncodingWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con codificaciones.</p>
<p>Consulte <a class="reference internal" href="io.html#io-encoding-warning"><span class="std std-ref">EncodingWarning opcional</span></a> para obtener más detalles.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.10.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt id="BytesWarning">
<em class="property">exception </em><code class="sig-name descname">BytesWarning</code><a class="headerlink" href="#BytesWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con <a class="reference internal" href="stdtypes.html#bytes" title="bytes"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytes</span></code></a> y <a class="reference internal" href="stdtypes.html#bytearray" title="bytearray"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytearray</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt id="ResourceWarning">
<em class="property">exception </em><code class="sig-name descname">ResourceWarning</code><a class="headerlink" href="#ResourceWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con el uso de recursos.</p>
<p>Ignorado por los filtros de advertencia predeterminados. Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.2.</span></p>
</div>
</dd></dl>

</section>
<section id="exception-hierarchy">
<h2>Jerarquía de excepción<a class="headerlink" href="#exception-hierarchy" title="Enlazar permanentemente con este título">¶</a></h2>
<p>La jerarquía de clases para las excepciones incorporadas es:</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="ne">BaseException</span>
 <span class="o">+--</span> <span class="ne">SystemExit</span>
 <span class="o">+--</span> <span class="ne">KeyboardInterrupt</span>
 <span class="o">+--</span> <span class="ne">GeneratorExit</span>
 <span class="o">+--</span> <span class="ne">Exception</span>
      <span class="o">+--</span> <span class="ne">StopIteration</span>
      <span class="o">+--</span> <span class="ne">StopAsyncIteration</span>
      <span class="o">+--</span> <span class="ne">ArithmeticError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FloatingPointError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">OverflowError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ZeroDivisionError</span>
      <span class="o">+--</span> <span class="ne">AssertionError</span>
      <span class="o">+--</span> <span class="ne">AttributeError</span>
      <span class="o">+--</span> <span class="ne">BufferError</span>
      <span class="o">+--</span> <span class="ne">EOFError</span>
      <span class="o">+--</span> <span class="ne">ImportError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ModuleNotFoundError</span>
      <span class="o">+--</span> <span class="ne">LookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndexError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">KeyError</span>
      <span class="o">+--</span> <span class="ne">MemoryError</span>
      <span class="o">+--</span> <span class="ne">NameError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnboundLocalError</span>
      <span class="o">+--</span> <span class="ne">OSError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BlockingIOError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ChildProcessError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BrokenPipeError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionAbortedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionRefusedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionResetError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileExistsError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileNotFoundError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">InterruptedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IsADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">PermissionError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ProcessLookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">TimeoutError</span>
      <span class="o">+--</span> <span class="ne">ReferenceError</span>
      <span class="o">+--</span> <span class="ne">RuntimeError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotImplementedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">RecursionError</span>
      <span class="o">+--</span> <span class="ne">SyntaxError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndentationError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">TabError</span>
      <span class="o">+--</span> <span class="ne">SystemError</span>
      <span class="o">+--</span> <span class="ne">TypeError</span>
      <span class="o">+--</span> <span class="ne">ValueError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnicodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeDecodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeEncodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeTranslateError</span>
      <span class="o">+--</span> <span class="ne">Warning</span>
           <span class="o">+--</span> <span class="ne">DeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">PendingDeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">RuntimeWarning</span>
           <span class="o">+--</span> <span class="ne">SyntaxWarning</span>
           <span class="o">+--</span> <span class="ne">UserWarning</span>
           <span class="o">+--</span> <span class="ne">FutureWarning</span>
           <span class="o">+--</span> <span class="ne">ImportWarning</span>
           <span class="o">+--</span> <span class="ne">UnicodeWarning</span>
           <span class="o">+--</span> <span class="ne">BytesWarning</span>
           <span class="o">+--</span> <span class="ne">EncodingWarning</span>
           <span class="o">+--</span> <span class="ne">ResourceWarning</span>
</pre></div>
</div>
</section>
</section>


            <div class="clearer"></div>
          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">Tabla de contenido</a></h3>
  <ul>
<li><a class="reference internal" href="#">Excepciones incorporadas</a><ul>
<li><a class="reference internal" href="#exception-context">Exception context</a></li>
<li><a class="reference internal" href="#inheriting-from-built-in-exceptions">Inheriting from built-in exceptions</a></li>
<li><a class="reference internal" href="#base-classes">Clases base</a></li>
<li><a class="reference internal" href="#concrete-exceptions">Excepciones específicas</a><ul>
<li><a class="reference internal" href="#os-exceptions">Excepciones del sistema operativo</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">Advertencias</a></li>
<li><a class="reference internal" href="#exception-hierarchy">Jerarquía de excepción</a></li>
</ul>
</li>
</ul>

  <h4>Tema anterior</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="capítulo anterior">Tipos Integrados</a></p>
  <h4>Próximo tema</h4>
  <p class="topless"><a href="text.html"
                        title="próximo capítulo">Servicios de procesamiento de texto</a></p>
  <div role="note" aria-label="source link">
    <h3>Esta página</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">Reporta un Bug</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.10/Doc/library/exceptions.rst"
            rel="nofollow">Ver Fuente
        </a>
      </li>
    </ul>
  </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navegación</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="Índice general"
             >índice</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Índice de Módulos Python"
             >módulos</a> |</li>
        <li class="right" >
          <a href="text.html" title="Servicios de procesamiento de texto"
             >siguiente</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="Tipos Integrados"
             >anterior</a> |</li>

          <li><img src="../_static/py.svg" alt="python logo" style="vertical-align: middle; margin-top: -1px"/></li>
          <li><a href="https://www.python.org/">Python</a> &#187;</li>
          <li class="switchers">
            <div class="language_switcher_placeholder"></div>
            <div class="version_switcher_placeholder"></div>
          </li>
          <li>
              
          </li>
    <li id="cpython-language-and-version">
      <a href="../index.html">3.10.10 Documentation</a> &#187;
    </li>

          <li class="nav-item nav-item-1"><a href="index.html" >La Biblioteca Estándar de Python</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">Excepciones incorporadas</a></li>
                <li class="right">
                    

    <div class="inline-search" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Búsqueda rápida" aria-label="Búsqueda rápida" type="text" name="q" />
          <input type="submit" value="Ir" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
                     |
                </li>
            
      </ul>
    </div>  
    <div class="footer">
    &copy; <a href="../copyright.html">Copyright</a> 2001-2023, Python Software Foundation.
    <br />
    This page is licensed under the Python Software Foundation License Version 2.
    <br />
    Examples, recipes, and other code in the documentation are additionally licensed under the Zero Clause BSD License.
    <br />
    See <a href="/license.html">History and License</a> for more information.<br />
    <br />

    La Python Software Foundation es una organización sin fines de lucro.
<a href="https://www.python.org/psf/donations/">Por favor, haga una donación.</a>
<br />
    <br />

    Última actualización el mar 27, 2023.
    <a href="/bugs.html">Found a bug</a>?
    <br />

    Created using <a href="https://www.sphinx-doc.org/">Sphinx</a> 3.4.3.
    </div>

  </body>
</html>